/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://cghkqrkrqvbnpjsbtvolua5ta4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6i25pqkwj5bqlig5ekspf7v2te",
    "aws_cognito_identity_pool_id": "us-east-2:30addfdd-5638-40c0-ad33-be5f7e8a6c2a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_pyaHyjyWE",
    "aws_user_pools_web_client_id": "2ohtjhtn714hojf3gbr1iked8t",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
